# Site settings
author: astonishing-panel-1637
title: 
header-img: img/home-bg.png
email: dr.erbil@protonmail.ch
copyright_name: astonishing-panel-1637
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  azraelatlanta

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
